data_file: "train_data.csv"
nsamples: 100
ngen: 5
random: False
rel_iter: 500
mlff: "m3gnet"
target: "Eform"
verbose: True
start: 0
wyckoff: /scratch16/pclancy3/divya/MaterialOracles/wyckoff.yaml
timer: True