data_file: "train_data.csv"
nsamples: 20
ngen: 5
random: False
rel_iter: 250
mlff: "m3gnet"
target: "Eform"
verbose: True
wyckoff: False
start: 0
# wyckoff: /home/minion/Documents/proxies/crystallograpy/crystallograpy/yaml/wyckoff.yaml
timer: True
